"""
Django settings for demo_web project.

Generated by 'django-admin startproject' using Django 5.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
from datetime import timedelta
import os
from kombu import Queue

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media') # 文件将存储在项目根目录下的 'media' 文件夹中

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-6%v%_8@88(8@1xw95_omex_=!vw99l)rp7jrw!bi79k23yc9iu"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = [
    'eb2158c07f31.ngrok-free.app', # 你的 ngrok 域名
    'localhost',
    '127.0.0.1',
]


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    'rest_framework',
    'rest_framework_simplejwt',
    'corsheaders',
    'api',
    'pdf_parser',
    'pgvector',
    'rag_retriever',
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    'corsheaders.middleware.CorsMiddleware',
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "demo_web.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / 'templates']
        ,
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "demo_web.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'ai4mw_web_db',
        'USER': 'postgres',
        'PASSWORD': '15905190993zjr',
        'HOST': 'localhost',
        'PORT': '5433',  # 5432为本地postgresql
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i1n/

LANGUAGE_CODE = "en-us"
TIME_ZONE = "UTC"
USE_I1N = True
USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


# CORS (跨域资源共享) 配置
CORS_ALLOWED_ORIGINS = [
    "https://eb2158c07f31.ngrok-free.app",
    "http://localhost:5173",
    "http://localhost:5174",
    "https://web-demo-dcr.pages.dev", # 你的Cloudflare前端域名
]

# CSRF 受信来源
CSRF_TRUSTED_ORIGINS = [
    "https://eb2158c07f31.ngrok-free.app",
    "https://web-demo-dcr.pages.dev/", # 你的Cloudflare前端域名
]

CORS_ALLOW_HEADERS = [
    'accept',
    'authorization',
    'content-type',
    'origin',
    'x-csrftoken',
    'x-requested-with',
    'ngrok-skip-browser-warning',
]


# REST_FRAMEWORK 配置
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticatedOrReadOnly',
    )
}

# 默认大模型配置
DEFAULT_LLM_API_URL = "https://api.deepseek.com"
DEFAULT_LLM_API_KEY = "sk-e6412d3957f44da9b3774f7149860c15"
DEFAULT_LLM_MODEL_NAME = "deepseek-chat"

DEFAULT_VLM_API_URL = "https://dashscope.aliyuncs.com/compatible-mode/v1"
DEFAULT_VLM_API_KEY = "sk-25073b1d5af2464292d41bfb04d92a7e" 
DEFAULT_VLM_MODEL_NAME = "qwen2.5-vl-72b-instruct"

DEFAULT_EMBEDDING_API_URL = "https://dashscope.aliyuncs.com/compatible-mode/v1" # (示例，请修改为您的Embedding模型URL)
DEFAULT_EMBEDDING_API_KEY = "sk-25073b1d5af2464292d41bfb04d92a7e" # (示例，请修改为您的API Key)
DEFAULT_EMBEDDING_MODEL_NAME = "text-embedding-v4" # (示例，请修改)
DEFAULT_EMBEDDING_DIMENSIONS = 1024 # (示例，请根据您的模型修改)
DEFAULT_EMBEDDING_BATCH_SIZE = 10

# SIMPLE_JWT 配置
SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=60),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=1),
    "ROTATE_REFRESH_TOKENS": False,
    "BLACKLIST_AFTER_ROTATION": False,
    "UPDATE_LAST_LOGIN": False,

    "ALGORITHM": "HS256",
    "SIGNING_KEY": SECRET_KEY,
    "VERIFYING_KEY": "",
    "AUDIENCE": None,
    "ISSUER": None,
    "JSON_ENCODER": None,
    "JWK_URL": None,
    "LEEWAY": 0,

    "AUTH_HEADER_TYPES": ("Bearer",),
    "AUTH_HEADER_NAME": "HTTP_AUTHORIZATION",
    "USER_ID_FIELD": "id",
    "USER_ID_CLAIM": "user_id",
    "USER_AUTHENTICATION_RULE": "rest_framework_simplejwt.authentication.default_user_authentication_rule",

    "AUTH_TOKEN_CLASSES": ("rest_framework_simplejwt.tokens.AccessToken",),
    "TOKEN_TYPE_CLAIM": "token_type",
    "TOKEN_USER_CLASS": "rest_framework_simplejwt.models.TokenUser",

    "JTI_CLAIM": "jti",

    "SLIDING_TOKEN_REFRESH_EXP_CLAIM": "refresh_exp",
    "SLIDING_TOKEN_LIFETIME": timedelta(minutes=5),
    "SLIDING_TOKEN_REFRESH_LIFETIME": timedelta(days=1),

    "TOKEN_OBTAIN_SERIALIZER": "rest_framework_simplejwt.serializers.TokenObtainPairSerializer",
    "TOKEN_REFRESH_SERIALIZER": "rest_framework_simplejwt.serializers.TokenRefreshSerializer",
    "TOKEN_VERIFY_SERIALIZER": "rest_framework_simplejwt.serializers.TokenVerifySerializer",
    "TOKEN_BLACKLIST_SERIALIZER": "rest_framework_simplejwt.serializers.TokenBlacklistSerializer",
    "SLIDING_TOKEN_OBTAIN_SERIALIZER": "rest_framework_simplejwt.serializers.TokenObtainSlidingSerializer",
    "SLIDING_TOKEN_REFRESH_SERIALIZER": "rest_framework_simplejwt.serializers.TokenRefreshSlidingSerializer",
}

# --- Celery 配置 ---
# 使用 Redis 作为 Broker
# 确保 Redis 服务正在运行 (默认: localhost:6379)
CELERY_BROKER_URL = 'redis://localhost:6379/0'
CELERY_RESULT_BACKEND = 'redis://localhost:6379/0'
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = TIME_ZONE # 使用 Django 的时区

CELERY_TASK_QUEUES = (
    Queue('celery', routing_key='celery'),
    Queue('stage1_text', routing_key='stage1.text'),
    Queue('stage2_vlm', routing_key='stage2.vlm'),
    Queue('stage3_chunking', routing_key='stage3.chunking'),
    Queue('stage4_extraction', routing_key='stage4.extraction'),
    Queue('stage5_param_extraction', routing_key='stage5.param_extraction'),
    Queue('stage6_param_fusion', routing_key='stage6.param_fusion'),
    Queue('stage7_image_association', routing_key='stage7.image'),
    Queue('stage8_mfg_standardization', routing_key='stage8.mfg'),
    Queue('stage9_classify', routing_key='stage9.classify'),
    Queue('stage10_graph_construction', routing_key='stage10.graph'),
)

# --- 任务路由 (9 阶段) ---
CELERY_TASK_ROUTES = {
    'pdf_parser.tasks.task_pipeline': {'queue': 'celery'},
    'pdf_parser.tasks.run_text_analysis_task': {'queue': 'stage1_text'},
    'pdf_parser.tasks.run_vlm_analysis_task': {'queue': 'stage2_vlm'},
    'pdf_parser.tasks.run_chunking_task': {'queue': 'stage3_chunking'},
    'pdf_parser.tasks.run_model_extraction_task': {'queue': 'stage4_extraction'},
    'pdf_parser.tasks.run_param_extraction_task': {'queue': 'stage5_param_extraction'},
    'pdf_parser.tasks.run_param_fusion_task': {'queue': 'stage6_param_fusion'},
    'pdf_parser.tasks.run_image_association_task': {'queue': 'stage7_image_association'},
    'pdf_parser.tasks.run_manufacturer_standardization_task': {'queue': 'stage8_mfg_standardization'},
    'pdf_parser.tasks.run_classify_device_task': {'queue': 'stage9_classify'},
    'pdf_parser.tasks.run_graph_construction_task': {'queue': 'stage10_graph_construction'}, # <--- 新增
}

# --- PDF 解析器 (pdf_parser) 配置 ---
# 是否启用 OCR (True/False)
PDF_PARSER_ENABLE_OCR = False
# 是否保存分页图片 (True/False)
PDF_PARSER_SAVE_PAGES = True
# 页面渲染DPI (e.g., 200)
PDF_PARSER_PAGE_DPI = 200

PDF_PARSER_MODEL_PATH = BASE_DIR / "docling_models"  # Docling 模型目录

# --- 阶段3：文本分块 (Chunking) 配置 ---
PDF_PARSER_CHUNKING = {
    # 是否在解析表格时清理多余的空格
    "CLEAN_TABLE_WHITESPACE": False,
    # 动态块大小的参数
    "MIN_CHUNK_SIZE": 100,
    "MAX_CHUNK_SIZE": 500,
    # 动态块大小乘数 (n * max_block_size)
    "N_FACTOR": 1.5,
    # 滑动窗口大小 (例如 2 表示 [chunk-1, chunk, chunk+1] 总共3个)
    "WINDOW_SIZE": 2
}

# --- 阶段4：型号抽取 (Model Extraction) 配置 ---
PDF_PARSER_MODEL_EXTRACTION = {
    # 用于并发调用 LLM API 的线程池工作线程数
    "MAX_WORKERS": 5,
    # LLM API 调用失败的最大重试次数
    "MAX_RETRIES": 3,
    # LLM 调用的 temperature
    "TEMPERATURE": 0.0,
}

# --- 阶段6：参数提取 (Param Extraction) 配置 ---
# (注意：LLM 配置复用 DEFAULT_LLM)
PDF_PARSER_PARAM_EXTRACTION = {
    # 失败重试次数 (与阶段4分开)
    "MAX_RETRIES": 3,
    # API 调用之间的礼貌性延迟（秒），避免速率限制
    "API_CALL_DELAY": 1.0,
    # LLM 调用的 temperature
    "TEMPERATURE": 0.2,
    # LLM 调用的 max_tokens
    "MAX_TOKENS": 8000
}

# --- 阶段6：参数融合 (Param Fusion) 配置 ---
PDF_PARSER_PARAM_FUSION = {
    # LLM API 调用超时（秒）
    "API_TIMEOUT_SECONDS": 60,
    # LLM API 调用失败的最大重试次数
    "MAX_API_RETRIES": 3,
    # 重试前的等待时间（秒）
    "RETRY_DELAY_SECONDS": 5,
}

# --- 阶段7：图片关联 (Image Association) 配置 ---
PDF_PARSER_IMAGE_ASSOCIATION = {
    "MAX_RETRIES": 3,
    "RETRY_DELAY_SECONDS": 5,
}

# --- 阶段8：厂商标准化 (Manufacturer Standardization) 配置 ---
PDF_PARSER_MANUFACTURER_STANDARDIZATION = {
    "MAX_LLM_RETRIES": 3,
    "RETRY_DELAY_SECONDS": 5,
}

# --- 新增：阶段9：器件分类 (Device Classification) 配置 ---
PDF_PARSER_CLASSIFICATION = {
    # LLM决策重试次数
    "MAX_LLM_RETRIES": 3,
    # 重试延迟
    "RETRY_DELAY_SECONDS": 5,
}

# --- 新增：阶段10：图谱构建 (Graph Construction) 配置 ---
PDF_PARSER_GRAPH_CONSTRUCTION = {
    "BATCH_SIZE": 500, # 数据库批量插入大小
    "MAX_LLM_RETRIES": 3,
    "RETRY_DELAY_SECONDS": 5,
    # (Embedding Batch Size 将从 DEFAULT_EMBEDDING 配置中读取)
}

# --- 新增：阶段RAG：检索增强生成 (RAG) 配置 ---
PDF_PARSER_RAG = {
    # 1. 检索参数 (来自您的 retriever.py)
    'TOP_P_PER_ENTITY': 3,       # (top_p_per_entity) 匹配种子实体的最接近节点
    'BFS_DEPTH': 4,              # (bfs_depth) 图谱搜索的最大跳数
    'TOP_K_ORPHANS_TO_BRIDGE': 3, # (top_k_orphans_to_bridge) 尝试桥接的孤儿节点数

    # 2. 评分权重 (来自您的 retriever.py, 移除了 user 要求的 degree)
    'CHUNK_SCORE_ALPHA': 0.6,       # 文本相似度 (sim) vs 图谱推荐度 (rec) 的权重
    'SEED_DENSITY_BONUS': 0.5,      # 路径中种子节点密度的奖励
    'TOP_REC_K_FOR_SIMILARITY': 5,  # 为图谱推荐的Chunk计算相似度的Top K
    'STRONG_CHUNK_RECOMMENDATION_BONUS': 0.25, # 图谱对已在文本结果中的chunk的奖励
    'WEAK_CHUNK_RECOMMENDATION_BONUS': 0.15,   # 图谱对未在文本结果中的chunk的奖励
    'TEXT_CONFIRMATION_BONUS': 0.5, # 文本搜索结果确认了图谱路径中实体的奖励
    'ENDORSEMENT_BASE_BONUS': 0.1,  # 桥接路径对主路径的基础奖励
    'ENDORSEMENT_DECAY_FACTOR': 0.85, # 桥接路径每长一跳的奖励衰减
}